### ISSUE TITLE
Mac OS X : certificate verify failed (Seahorse::Client::NetworkingError)

### ISSUE THREAD

**Issue by llange** [dtan4/terraforming#171]
Hello,

On Mac OS X I have the following error :
```
/Users/llange/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:923:in `connect': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (Seahorse::Client::NetworkingError)
	from /Users/llange/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:923:in `block in connect'
	from /Users/llange/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:89:in `block in timeout'
	from /Users/llange/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:99:in `call'
	from /Users/llange/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:99:in `timeout'
	from /Users/llange/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:923:in `connect'
	from /Users/llange/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
	from /Users/llange/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:858:in `start'
...
```

It seems linked with the [following issue of aws-sdk-core](https://github.com/aws/aws-sdk-core-ruby/issues/166#issuecomment-111603660) and the fix suggested does indeed work.

If there is no adverse impact, could you please add the suggested fix ?

I added it to master/lib/terraforming.rb, just after the "require":
```
@@ -2,6 +2,7 @@
 require "ox"

 require "aws-sdk-core"
+Aws.use_bundled_cert!

 require "erb"
 require "json"
```

Thanks.

**Comment by OliverCole** [comment]
Reproduced on Windows:

```
c:/Ruby22/lib/ruby/2.2.0/net/http.rb:923:in `connect': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (Seahorse::Client::NetworkingError)
        from c:/Ruby22/lib/ruby/2.2.0/net/http.rb:923:in `block in connect'
...
        from c:/Ruby22/lib/ruby/gems/2.2.0/gems/aws-sdk-core-2.3.19/lib/seahorse/client/net_http/connection_pool.rb:281:in `start_session'
...
        from c:/Ruby22/lib/ruby/gems/2.2.0/gems/terraforming-0.9.1/lib/terraforming/resource/route53_zone.rb:52:in `hosted_zones'
        from (erb):1:in `apply_template'
        from c:/Ruby22/lib/ruby/2.2.0/erb.rb:863:in `eval'
        from c:/Ruby22/lib/ruby/2.2.0/erb.rb:863:in `result'
        from c:/Ruby22/lib/ruby/gems/2.2.0/gems/terraforming-0.9.1/lib/terraforming/util.rb:4:in `apply_template'
        from c:/Ruby22/lib/ruby/gems/2.2.0/gems/terraforming-0.9.1/lib/terraforming/resource/route53_zone.rb:19:in `tf'
        from c:/Ruby22/lib/ruby/gems/2.2.0/gems/terraforming-0.9.1/lib/terraforming/resource/route53_zone.rb:7:in `tf'
        from c:/Ruby22/lib/ruby/gems/2.2.0/gems/terraforming-0.9.1/lib/terraforming/cli.rb:203:in `tf'
        from c:/Ruby22/lib/ruby/gems/2.2.0/gems/terraforming-0.9.1/lib/terraforming/cli.rb:190:in `execute'
        from c:/Ruby22/lib/ruby/gems/2.2.0/gems/terraforming-0.9.1/lib/terraforming/cli.rb:131:in `r53z'
        from c:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from c:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from c:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from c:/Ruby22/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from c:/Ruby22/lib/ruby/gems/2.2.0/gems/terraforming-0.9.1/bin/terraforming:5:in `<top (required)>'
        from c:/Ruby22/bin/terraforming:23:in `load'
        from c:/Ruby22/bin/terraforming:23:in `<main>'
```
