### ISSUE TITLE
merge fails if outputting into merge source

### ISSUE THREAD

**Issue by atomantic** [dtan4/terraforming#195]
create initial state file
```
⇒  terraforming vpc --profile default --tfstate > terraform.tfstate
```
ask for another, merging the first into a new file (all good)
```
⇒  terraforming asg --profile default --tfstate --merge=terraform.tfstate > terraform.tfstates
```
repeat, but this time merge into the merge source file (failed)
```
⇒  terraforming asg --profile default --tfstate --merge=terraform.tfstate > terraform.tfstate
/usr/local/lib/ruby/gems/2.3.0/gems/json_pure-1.8.3/lib/json/common.rb:155:in `initialize': A JSON text must at least contain two octets! (JSON::ParserError)
	from /usr/local/lib/ruby/gems/2.3.0/gems/json_pure-1.8.3/lib/json/common.rb:155:in `new'
	from /usr/local/lib/ruby/gems/2.3.0/gems/json_pure-1.8.3/lib/json/common.rb:155:in `parse'
	from /usr/local/lib/ruby/gems/2.3.0/gems/terraforming-0.7.0/lib/terraforming/cli.rb:184:in `tfstate'
	from /usr/local/lib/ruby/gems/2.3.0/gems/terraforming-0.7.0/lib/terraforming/cli.rb:167:in `execute'
	from /usr/local/lib/ruby/gems/2.3.0/gems/terraforming-0.7.0/lib/terraforming/cli.rb:10:in `asg'
	from /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /usr/local/lib/ruby/gems/2.3.0/gems/terraforming-0.7.0/bin/terraforming:5:in `<top (required)>'
	from /usr/local/bin/terraforming:23:in `load'
	from /usr/local/bin/terraforming:23:in `<main>'
```

**Comment by atomantic** [comment]
nevermind. I RTFM'd and found that --overwrite works :)
