### ISSUE TITLE
aws-sdk-core/endpoint_provider.rb:67:in `block in partition_matching_region': undefined method `match' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by bendavies** [dtan4/terraforming#235]
Just installed and get this error.
I'm not a ruby developer, so not sure what information i can provide. let me know!
```
terraforming ec2
/usr/local/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.3.14/lib/aws-sdk-core/endpoint_provider.rb:67:in `block in partition_matching_region': undefined method `match' for nil:NilClass (NoMethodError)
Did you mean?  catch
	from /usr/local/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.3.14/lib/aws-sdk-core/endpoint_provider.rb:66:in `each'
	from /usr/local/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.3.14/lib/aws-sdk-core/endpoint_provider.rb:66:in `find'
	from /usr/local/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.3.14/lib/aws-sdk-core/endpoint_provider.rb:66:in `partition_matching_region'
	from /usr/local/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.3.14/lib/aws-sdk-core/endpoint_provider.rb:55:in `get_partition'
	from /usr/local/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.3.14/lib/aws-sdk-core/endpoint_provider.rb:26:in `endpoint_for'
	from /usr/local/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.3.14/lib/aws-sdk-core/endpoint_provider.rb:10:in `resolve'
	from /usr/local/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.3.14/lib/aws-sdk-core/endpoint_provider.rb:80:in `resolve'
	from /usr/local/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.3.14/lib/aws-sdk-core/plugins/regional_endpoint.rb:24:in `block in <class:RegionalEndpoint>'
	from /usr/local/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.3.14/lib/seahorse/client/configuration.rb:70:in `call'
	from /usr/local/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.3.14/lib/seahorse/client/configuration.rb:205:in `block in resolve_defaults'
	from /usr/local/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.3.14/lib/seahorse/client/configuration.rb:57:in `each'
	from /usr/local/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.3.14/lib/seahorse/client/configuration.rb:57:in `each'
	from /usr/local/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.3.14/lib/seahorse/client/configuration.rb:204:in `resolve_defaults'
	from /usr/local/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.3.14/lib/seahorse/client/configuration.rb:200:in `value_at'
	from /usr/local/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.3.14/lib/seahorse/client/configuration.rb:189:in `block in resolve'
	from /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/set.rb:306:in `each_key'
	from /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/set.rb:306:in `each'
	from /usr/local/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.3.14/lib/seahorse/client/configuration.rb:189:in `resolve'
	from /usr/local/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.3.14/lib/seahorse/client/configuration.rb:177:in `apply_defaults'
	from /usr/local/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.3.14/lib/seahorse/client/configuration.rb:150:in `build!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.3.14/lib/seahorse/client/base.rb:68:in `build_config'
	from /usr/local/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.3.14/lib/seahorse/client/base.rb:19:in `initialize'
	from /usr/local/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.3.14/lib/seahorse/client/base.rb:105:in `new'
	from /usr/local/lib/ruby/gems/2.3.0/gems/terraforming-0.9.1/lib/terraforming/resource/ec2.rb:6:in `tf'
	from /usr/local/lib/ruby/gems/2.3.0/gems/terraforming-0.9.1/lib/terraforming/cli.rb:203:in `tf'
	from /usr/local/lib/ruby/gems/2.3.0/gems/terraforming-0.9.1/lib/terraforming/cli.rb:190:in `execute'
	from /usr/local/lib/ruby/gems/2.3.0/gems/terraforming-0.9.1/lib/terraforming/cli.rb:31:in `ec2'
	from /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /usr/local/lib/ruby/gems/2.3.0/gems/terraforming-0.9.1/bin/terraforming:5:in `<top (required)>'
	from /usr/local/bin/terraforming:23:in `load'
	from /usr/local/bin/terraforming:23:in `<main>'
```

**Comment by bendavies** [comment]
avoided this by specifying the region .
`terraforming ec2 --region=us-west-2`

**Comment by dtan4** [comment]
Sorry for late reply.

I reproduce this error, without setting 'AWS_REGION' environment variable. This is an error of AWS SDK, not of Terraforming itself.

Please set `AWS_REGION=us-west-2` environment variable and it should work well 💡 

If you still have the same error, please reopen this issue.
Thanks.
