### ISSUE TITLE
terraforming rds fails, undefined method "port"

### ISSUE THREAD

**Issue by SPhu** [dtan4/terraforming#268]
**running:** terraforming rds --profile default

**results in:**
(erb):12:in `block in apply_template': undefined method `port' for nil:NilClass (NoMethodError)
	from (erb):1:in `each'
	from (erb):1:in `apply_template'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/erb.rb:849:in `eval'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/erb.rb:849:in `result'
	from /Library/Ruby/Gems/2.0.0/gems/terraforming-0.10.0/lib/terraforming/util.rb:4:in `apply_template'
	from /Library/Ruby/Gems/2.0.0/gems/terraforming-0.10.0/lib/terraforming/resource/rds.rb:19:in `tf'
	from /Library/Ruby/Gems/2.0.0/gems/terraforming-0.10.0/lib/terraforming/resource/rds.rb:7:in `tf'
	from /Library/Ruby/Gems/2.0.0/gems/terraforming-0.10.0/lib/terraforming/cli.rb:215:in `tf'
	from /Library/Ruby/Gems/2.0.0/gems/terraforming-0.10.0/lib/terraforming/cli.rb:202:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/terraforming-0.10.0/lib/terraforming/cli.rb:144:in `rds'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/terraforming-0.10.0/bin/terraforming:5:in `<top (required)>'
	from /usr/bin/terraforming:23:in `load'
	from /usr/bin/terraforming:23:in `<main>'

**Comment by liammac** [comment]
seeing the same thing for RedShift

```
(erb):15:in `block in apply_template': undefined method `port' for nil:NilClass (NoMethodError)
        from (erb):1:in `each'
        from (erb):1:in `apply_template'
        from /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/erb.rb:864:in `eval'
        from /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/erb.rb:864:in `result'
        from /usr/local/lib/ruby/gems/2.3.0/gems/terraforming-0.10.0/lib/terraforming/util.rb:4:in `apply_template'
        from /usr/local/lib/ruby/gems/2.3.0/gems/terraforming-0.10.0/lib/terraforming/resource/redshift.rb:19:in `tf'
        from /usr/local/lib/ruby/gems/2.3.0/gems/terraforming-0.10.0/lib/terraforming/resource/redshift.rb:7:in `tf'
        from /usr/local/lib/ruby/gems/2.3.0/gems/terraforming-0.10.0/lib/terraforming/cli.rb:215:in `tf'
        from /usr/local/lib/ruby/gems/2.3.0/gems/terraforming-0.10.0/lib/terraforming/cli.rb:202:in `execute'
        from /usr/local/lib/ruby/gems/2.3.0/gems/terraforming-0.10.0/lib/terraforming/cli.rb:149:in `rs'
        from /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /usr/local/lib/ruby/gems/2.3.0/gems/terraforming-0.10.0/bin/terraforming:5:in `<top (required)>'
        from /usr/local/bin/terraforming:23:in `load'
        from /usr/local/bin/terraforming:23:in `<main>'
```

**Comment by seanknox** [comment]
This happens when the RDS or Redshift DB is still in the provisioning phase. Try again once it's up.

**Comment by darkn3rd** [comment]
I am seeing this issue as well.  MySQL 5.6 database.

```bash
terraforming rds --profile=$AWS_DEFAULT_PROFILE --region=us-east-2
Traceback (most recent call last):
	17: from /Users/mejoaqui/.rbenv/versions/2.6.2/bin/terraforming:23:in `<main>'
	16: from /Users/mejoaqui/.rbenv/versions/2.6.2/bin/terraforming:23:in `load'
	15: from /Users/mejoaqui/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/terraforming-0.16.0/bin/terraforming:5:in `<top (required)>'
	14: from /Users/mejoaqui/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	13: from /Users/mejoaqui/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	12: from /Users/mejoaqui/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	11: from /Users/mejoaqui/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	10: from /Users/mejoaqui/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/terraforming-0.16.0/lib/terraforming/cli.rb:170:in `rds'
	 9: from /Users/mejoaqui/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/terraforming-0.16.0/lib/terraforming/cli.rb:245:in `execute'
	 8: from /Users/mejoaqui/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/terraforming-0.16.0/lib/terraforming/cli.rb:258:in `tf'
	 7: from /Users/mejoaqui/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/terraforming-0.16.0/lib/terraforming/resource/rds.rb:7:in `tf'
	 6: from /Users/mejoaqui/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/terraforming-0.16.0/lib/terraforming/resource/rds.rb:19:in `tf'
	 5: from /Users/mejoaqui/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/terraforming-0.16.0/lib/terraforming/util.rb:4:in `apply_template'
	 4: from /Users/mejoaqui/.rbenv/versions/2.6.2/lib/ruby/2.6.0/erb.rb:901:in `result'
	 3: from /Users/mejoaqui/.rbenv/versions/2.6.2/lib/ruby/2.6.0/erb.rb:901:in `eval'
	 2: from (erb):1:in `apply_template'
	 1: from (erb):1:in `each'
(erb):12:in `block in apply_template': undefined method `port' for nil:NilClass (NoMethodError)
```
