### ISSUE TITLE
Unable to configure Terraforming 

### ISSUE THREAD

**Issue by NitinPatilNorthgate** [dtan4/terraforming#269]
I'm trying to setup Terraforming on Ubuntu, I have installed developer essentials and supported rubygem  but still getting error while running simple command.

Output:
```
ubuntu@ip-10-12-0-58:~$ terraforming s3 --profile default
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': /var/lib/gems/1.9.1/gems/terraforming-0.10.0/lib/terraforming/util.rb:20: syntax error, unexpected tLABEL (SyntaxError)
    def prettify_policy(document, breakline: false, unescape: false)
                                            ^
/var/lib/gems/1.9.1/gems/terraforming-0.10.0/lib/terraforming/util.rb:20: Can't assign to false
    def prettify_policy(document, breakline: false, unescape: false)
                                                   ^
/var/lib/gems/1.9.1/gems/terraforming-0.10.0/lib/terraforming/util.rb:30: syntax error, unexpected keyword_end, expecting $end
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /var/lib/gems/1.9.1/gems/terraforming-0.10.0/lib/terraforming.rb:17:in `<top (required)>'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /var/lib/gems/1.9.1/gems/terraforming-0.10.0/bin/terraforming:3:in `<top (required)>'
        from /usr/local/bin/terraforming:23:in `load'
        from /usr/local/bin/terraforming:23:in `<main>'

```

**Comment by NitinPatilNorthgate** [comment]
To solve this issue I installed newer version of Ruby using following commands

#Install RubyGems to use gems front-end of RubyGems
sudo apt-add-repository ppa:brightbox/ruby-ng
sudo apt-get update
sudo apt-get install ruby2.2 ruby2.2-dev

**Comment by msharma24** [comment]
I removed the ruby 1.9.x and installed ruby2.2 from the above mentioned commands.
