### ISSUE TITLE
Add Assume Role functionality

### ISSUE THREAD

**Issue by gstlt** [dtan4/terraforming#280]
Sample configuration .aws/credentials:
`
[default]
aws_access_key_id = <THEKEY>
aws_secret_access_key = <THESECRET>
aws_session_token = <MFA_TOKEN>

[assume_admin_role]
source_profile = default
role_arn = arn:aws:iam::123456789012:role/SomeAdminRole
`

Error:
`$ terraforming iamg --profile=default --region=eu-west-1
/home/gstlt/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.5.11/lib/aws-sdk-core/plugins/request_signer.rb:100:in `require_credentials': unable to sign request without credentials set (Aws::Errors::MissingCredentialsError)
	from /home/gstlt/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.5.11/lib/aws-sdk-core/plugins/request_signer.rb:90:in `sign_authenticated_requests'
	from /home/gstlt/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.5.11/lib/aws-sdk-core/plugins/request_signer.rb:83:in `call'
	from /home/gstlt/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.5.11/lib/aws-sdk-core/plugins/helpful_socket_errors.rb:10:in `call'
	from /home/gstlt/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.5.11/lib/aws-sdk-core/plugins/retry_errors.rb:87:in `call'
	from /home/gstlt/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.5.11/lib/aws-sdk-core/query/handler.rb:27:in `call'
	from /home/gstlt/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.5.11/lib/aws-sdk-core/plugins/user_agent.rb:12:in `call'
	from /home/gstlt/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.5.11/lib/seahorse/client/plugins/endpoint.rb:41:in `call'
	from /home/gstlt/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.5.11/lib/aws-sdk-core/plugins/param_validator.rb:21:in `call'
	from /home/gstlt/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.5.11/lib/seahorse/client/plugins/raise_response_errors.rb:14:in `call'
	from /home/gstlt/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.5.11/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
	from /home/gstlt/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.5.11/lib/aws-sdk-core/plugins/response_paging.rb:26:in `call'
	from /home/gstlt/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.5.11/lib/seahorse/client/plugins/response_target.rb:21:in `call'
	from /home/gstlt/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.5.11/lib/seahorse/client/request.rb:70:in `send_request'
	from /home/gstlt/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.5.11/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
	from /home/gstlt/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/terraforming-0.10.0/lib/terraforming/resource/iam_group.rb:46:in `iam_groups'
	from (erb):1:in `apply_template'
	from /home/gstlt/.rbenv/versions/2.3.1/lib/ruby/2.3.0/erb.rb:864:in `eval'
	from /home/gstlt/.rbenv/versions/2.3.1/lib/ruby/2.3.0/erb.rb:864:in `result'
	from /home/gstlt/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/terraforming-0.10.0/lib/terraforming/util.rb:4:in `apply_template'
	from /home/gstlt/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/terraforming-0.10.0/lib/terraforming/resource/iam_group.rb:19:in `tf'
	from /home/gstlt/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/terraforming-0.10.0/lib/terraforming/resource/iam_group.rb:7:in `tf'
	from /home/gstlt/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/terraforming-0.10.0/lib/terraforming/cli.rb:215:in `tf'
	from /home/gstlt/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/terraforming-0.10.0/lib/terraforming/cli.rb:202:in `execute'
	from /home/gstlt/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/terraforming-0.10.0/lib/terraforming/cli.rb:59:in `iamg'
	from /home/gstlt/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /home/gstlt/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/gstlt/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /home/gstlt/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /home/gstlt/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/terraforming-0.10.0/bin/terraforming:5:in `<top (required)>'
	from /home/gstlt/.rbenv/versions/2.3.1/bin/terraforming:23:in `load'
	from /home/gstlt/.rbenv/versions/2.3.1/bin/terraforming:23:in `<main>'

`

After moving role to [default] profile:
`$ terraforming iamg --profile=default --region=eu-west-1
/home/gstlt/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.5.11/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call': User: arn:aws:iam::123456789012:user/login.name is not authorized to perform: iam:ListGroups on resource: arn:aws:iam::927804118088:group/ (Aws::IAM::Errors::AccessDenied)
	from /home/gstlt/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.5.11/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
	from /home/gstlt/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.5.11/lib/aws-sdk-core/plugins/response_paging.rb:26:in `call'
	from /home/gstlt/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.5.11/lib/seahorse/client/plugins/response_target.rb:21:in `call'
	from /home/gstlt/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.5.11/lib/seahorse/client/request.rb:70:in `send_request'
	from /home/gstlt/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.5.11/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
	from /home/gstlt/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/terraforming-0.10.0/lib/terraforming/resource/iam_group.rb:46:in `iam_groups'
	from (erb):1:in `apply_template'
	from /home/gstlt/.rbenv/versions/2.3.1/lib/ruby/2.3.0/erb.rb:864:in `eval'
	from /home/gstlt/.rbenv/versions/2.3.1/lib/ruby/2.3.0/erb.rb:864:in `result'
	from /home/gstlt/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/terraforming-0.10.0/lib/terraforming/util.rb:4:in `apply_template'
	from /home/gstlt/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/terraforming-0.10.0/lib/terraforming/resource/iam_group.rb:19:in `tf'
	from /home/gstlt/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/terraforming-0.10.0/lib/terraforming/resource/iam_group.rb:7:in `tf'
	from /home/gstlt/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/terraforming-0.10.0/lib/terraforming/cli.rb:215:in `tf'
	from /home/gstlt/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/terraforming-0.10.0/lib/terraforming/cli.rb:202:in `execute'
	from /home/gstlt/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/terraforming-0.10.0/lib/terraforming/cli.rb:59:in `iamg'
	from /home/gstlt/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /home/gstlt/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/gstlt/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /home/gstlt/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /home/gstlt/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/terraforming-0.10.0/bin/terraforming:5:in `<top (required)>'
	from /home/gstlt/.rbenv/versions/2.3.1/bin/terraforming:23:in `load'
	from /home/gstlt/.rbenv/versions/2.3.1/bin/terraforming:23:in `<main>'

`

Am I missing something or Assume Role is not working right now?

Thanks!

**Comment by ThatGerber** [comment]
The `aws_session_token` is a generated temporary token, not your MFA token. `aws_session_token` is generated as temporary authorization after authenticating with your MFA device.

http://docs.aws.amazon.com/cli/latest/topic/config-vars.html#credentials

**Comment by gstlt** [comment]
So I've updated description. It's not a PEBKAC, MFA+assume role works fine for AWS CLI.

**Comment by failure84** [comment]
leave the = away, like: 

terraforming iamg --profile default --region eu-west-1

**Comment by gstlt** [comment]
I'm running at the moment on entirely different setup and not using terraforming as I'm building terraform from scratch. I won't be able to confirm if any suggestion will work.

I'm not closing it for a reference, maybe someone else will have the same issue with MFA and terraforming.
Thanks a lot!

**Comment by cmedley** [comment]
I needed to assume role and added this way
https://github.com/cmedley/terraforming/commit/a7f06727a9082e41c7ad47d5b2709fefb1fee677

if it looks good, will write tests and do PR

**Comment by jamengual** [comment]
I'm having this problem and I can do any testing you want, we use an auth account from where we assume role to other accounts.

I tried to use aws-vault so that I can pass ENV variables to terraforming but still complains.

I use aws-vault with terraform due to the lack of support for MFA and it works perfectly since terraform respect the standard AWS ENV variables that seems terraforming does not.
