### ISSUE TITLE
Error at launch

### ISSUE THREAD

**Issue by Cramix** [dtan4/terraforming#308]
Hello,

I installed Terraforming with the gem install command (0.13.1) and when I run any terraforming command, I get the following error:

This is on an Ubuntu machine, but it works great on macos (0.13.1 too)
```
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': /var/lib/gems/1.9.1/gems/terraforming-0.13.1/lib/terraforming/util.rb:20: syntax error, unexpected tLABEL (SyntaxError)
    def prettify_policy(document, breakline: false, unescape: false)
                                            ^
/var/lib/gems/1.9.1/gems/terraforming-0.13.1/lib/terraforming/util.rb:20: Can't assign to false
    def prettify_policy(document, breakline: false, unescape: false)
                                                   ^
/var/lib/gems/1.9.1/gems/terraforming-0.13.1/lib/terraforming/util.rb:30: syntax error, unexpected keyword_end, expecting $end
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /var/lib/gems/1.9.1/gems/terraforming-0.13.1/lib/terraforming.rb:7:in `<top (required)>'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /var/lib/gems/1.9.1/gems/terraforming-0.13.1/bin/terraforming:3:in `<top (required)>'
	from /usr/local/bin/terraforming:23:in `load'
	from /usr/local/bin/terraforming:23:in `<main>'
```

What am I doing wrong?

**Comment by dtan4** [comment]
As described at https://github.com/dtan4/terraforming#supported-version, Terraform supports Ruby 2.1 or higher only. It seems that your Ruby is 1.9.1, which is no longer supported officially.

Please use the latest Ruby, or consider using [Docker image](https://github.com/dtan4/dockerfile-terraforming).

**Comment by Cramix** [comment]
Thank you, it works now!
Sorry for the stupid question

**Comment by dtan4** [comment]
No problem! Thank you for using Terraforming 😃
