### ISSUE TITLE
Terraforming EIP seems to fail

### ISSUE THREAD

**Issue by tanhaa** [dtan4/terraforming#317]
Terraforming EIP seems to fail with a ruby stack trace below.  

```
 $ terraforming eip
/Library/Ruby/Gems/2.0.0/gems/terraforming-0.13.1/lib/terraforming/util.rb:13:in `normalize_module_name': undefined method `gsub' for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/terraforming-0.13.1/lib/terraforming/resource/eip.rb:58:in `module_name_of'
	from (erb):2:in `block in apply_template'
	from (erb):1:in `each'
	from (erb):1:in `apply_template'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/erb.rb:849:in `eval'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/erb.rb:849:in `result'
	from /Library/Ruby/Gems/2.0.0/gems/terraforming-0.13.1/lib/terraforming/util.rb:4:in `apply_template'
	from /Library/Ruby/Gems/2.0.0/gems/terraforming-0.13.1/lib/terraforming/resource/eip.rb:19:in `tf'
	from /Library/Ruby/Gems/2.0.0/gems/terraforming-0.13.1/lib/terraforming/resource/eip.rb:7:in `tf'
	from /Library/Ruby/Gems/2.0.0/gems/terraforming-0.13.1/lib/terraforming/cli.rb:240:in `tf'
	from /Library/Ruby/Gems/2.0.0/gems/terraforming-0.13.1/lib/terraforming/cli.rb:227:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/terraforming-0.13.1/lib/terraforming/cli.rb:59:in `eip'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/terraforming-0.13.1/bin/terraforming:5:in `<top (required)>'
	from /usr/local/bin/terraforming:23:in `load'
	from /usr/local/bin/terraforming:23:in `<main>'
```

**Comment by yn** [comment]
Fixed in https://github.com/dtan4/terraforming/pull/316

**Comment by tchia04** [comment]
There has not been any release since Jan 2017. The Fix in #316 was merged in March. Could we get a new build?

**Comment by dtan4** [comment]
Sorry for late! I just released the new version v0.13.2. Please try :octocat:

**Comment by yn** [comment]
I think this issue can be closed.
