### ISSUE TITLE
unable to connect to `elasticfilesystem.eu-central-1.amazonaws.com`; SocketError: getaddrinfo: nodename nor servname provided, or not known (Seahorse::Client::NetworkingError)

### ISSUE THREAD

**Issue by grebois** [dtan4/terraforming#334]
Trying to run:

$ terraforming help | grep terraforming | grep -v help | awk '{print "terraforming", $2, ">", $2".tf";}' | bash

I keep getting:

```
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:878:in `initialize': unable to connect to `elasticfilesystem.eu-central-1.amazonaws.com`; SocketError: getaddrinfo: nodename nor servname provided, or not known (Seahorse::Client::NetworkingError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:878:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:878:in `block in connect'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:877:in `connect'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:862:in `do_start'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:857:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/aws-sdk-core-2.9.16/lib/seahorse/client/net_http/connection_pool.rb:285:in `start_session'
	from /Library/Ruby/Gems/2.0.0/gems/aws-sdk-core-2.9.16/lib/seahorse/client/net_http/connection_pool.rb:92:in `session_for'
	from /Library/Ruby/Gems/2.0.0/gems/aws-sdk-core-2.9.16/lib/seahorse/client/net_http/handler.rb:119:in `session'
	from /Library/Ruby/Gems/2.0.0/gems/aws-sdk-core-2.9.16/lib/seahorse/client/net_http/handler.rb:71:in `transmit'
	from /Library/Ruby/Gems/2.0.0/gems/aws-sdk-core-2.9.16/lib/seahorse/client/net_http/handler.rb:45:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/aws-sdk-core-2.9.16/lib/seahorse/client/plugins/content_length.rb:12:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/aws-sdk-core-2.9.16/lib/aws-sdk-core/json/error_handler.rb:8:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/aws-sdk-core-2.9.16/lib/aws-sdk-core/plugins/request_signer.rb:88:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/aws-sdk-core-2.9.16/lib/aws-sdk-core/plugins/helpful_socket_errors.rb:10:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/aws-sdk-core-2.9.16/lib/aws-sdk-core/plugins/retry_errors.rb:88:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/aws-sdk-core-2.9.16/lib/aws-sdk-core/plugins/retry_errors.rb:119:in `retry_request'
	from /Library/Ruby/Gems/2.0.0/gems/aws-sdk-core-2.9.16/lib/aws-sdk-core/plugins/retry_errors.rb:102:in `retry_if_possible'
	from /Library/Ruby/Gems/2.0.0/gems/aws-sdk-core-2.9.16/lib/aws-sdk-core/plugins/retry_errors.rb:90:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/aws-sdk-core-2.9.16/lib/aws-sdk-core/plugins/retry_errors.rb:119:in `retry_request'
	from /Library/Ruby/Gems/2.0.0/gems/aws-sdk-core-2.9.16/lib/aws-sdk-core/plugins/retry_errors.rb:102:in `retry_if_possible'
	from /Library/Ruby/Gems/2.0.0/gems/aws-sdk-core-2.9.16/lib/aws-sdk-core/plugins/retry_errors.rb:90:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/aws-sdk-core-2.9.16/lib/aws-sdk-core/plugins/retry_errors.rb:119:in `retry_request'
	from /Library/Ruby/Gems/2.0.0/gems/aws-sdk-core-2.9.16/lib/aws-sdk-core/plugins/retry_errors.rb:102:in `retry_if_possible'
	from /Library/Ruby/Gems/2.0.0/gems/aws-sdk-core-2.9.16/lib/aws-sdk-core/plugins/retry_errors.rb:90:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/aws-sdk-core-2.9.16/lib/aws-sdk-core/rest/handler.rb:7:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/aws-sdk-core-2.9.16/lib/aws-sdk-core/plugins/user_agent.rb:12:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/aws-sdk-core-2.9.16/lib/seahorse/client/plugins/endpoint.rb:41:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/aws-sdk-core-2.9.16/lib/aws-sdk-core/plugins/param_validator.rb:21:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/aws-sdk-core-2.9.16/lib/seahorse/client/plugins/raise_response_errors.rb:14:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/aws-sdk-core-2.9.16/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/aws-sdk-core-2.9.16/lib/aws-sdk-core/plugins/idempotency_token.rb:18:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/aws-sdk-core-2.9.16/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/aws-sdk-core-2.9.16/lib/seahorse/client/plugins/response_target.rb:21:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/aws-sdk-core-2.9.16/lib/seahorse/client/request.rb:70:in `send_request'
	from /Library/Ruby/Gems/2.0.0/gems/aws-sdk-core-2.9.16/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
	from /Library/Ruby/Gems/2.0.0/gems/terraforming-0.13.2/lib/terraforming/resource/efs_file_system.rb:52:in `file_systems'
	from (erb):1:in `apply_template'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/erb.rb:849:in `eval'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/erb.rb:849:in `result'
	from /Library/Ruby/Gems/2.0.0/gems/terraforming-0.13.2/lib/terraforming/util.rb:4:in `apply_template'
	from /Library/Ruby/Gems/2.0.0/gems/terraforming-0.13.2/lib/terraforming/resource/efs_file_system.rb:19:in `tf'
	from /Library/Ruby/Gems/2.0.0/gems/terraforming-0.13.2/lib/terraforming/resource/efs_file_system.rb:7:in `tf'
	from /Library/Ruby/Gems/2.0.0/gems/terraforming-0.13.2/lib/terraforming/cli.rb:240:in `tf'
	from /Library/Ruby/Gems/2.0.0/gems/terraforming-0.13.2/lib/terraforming/cli.rb:227:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/terraforming-0.13.2/lib/terraforming/cli.rb:64:in `efs'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/terraforming-0.13.2/bin/terraforming:5:in `<top (required)>'
	from /usr/local/bin/terraforming:23:in `load'
	from /usr/local/bin/terraforming:23:in `<main>'```

**Comment by dtan4** [comment]
It seems that domain `elasticfilesystem.eu-central-1.amazonaws.com` was not resolved due to your network problem. Thanks!
