### ISSUE TITLE
Error with the Gem?

### ISSUE THREAD

**Issue by stack72** [dtan4/terraforming#34]
Just got linked to this on twitter, ran gem install terraforming

and when running the command *terraforming*

I get this error:

```
/opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/terraforming-0.0.1/lib/terraforming/util.rb:1:in `<top (required)>': uninitialized constant Terraforming (NameError)
	from /opt/rubies/2.0.0-p451/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /opt/rubies/2.0.0-p451/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/terraforming-0.0.1/lib/terraforming.rb:9:in `<top (required)>'
	from /opt/rubies/2.0.0-p451/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /opt/rubies/2.0.0-p451/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/terraforming-0.0.1/bin/terraforming:3:in `<top (required)>'
	from /opt/boxen/rbenv/versions/2.0.0-p451/bin/terraforming:23:in `load'
	from /opt/boxen/rbenv/versions/2.0.0-p451/bin/terraforming:23:in `<main>'
```

Am I missing something?

**Comment by dtan4** [comment]
Sorry, this is a bug of Terraforming.

I fixed this at #35 , and released it as v0.0.2.
Please try again with new version :bow: 

```bash
$ gem install terraforming -v 0.0.2
```

**Comment by stack72** [comment]
@dtan4 this works thanks :)

**Comment by dtan4** [comment]
:+1: 
Thank you for reporting issue!
