### ISSUE TITLE
Variables in IAM policies need to be escaped

### ISSUE THREAD

**Issue by seren** [dtan4/terraforming#367]
Hi, thanks for the incredibly useful tool. I just ran into the issue where variables in IAM policies need to be escaped (ex. "arn:aws:iam::1234567890:user/${aws:username}").

This is [discussed in the terraform repo](https://github.com/hashicorp/terraform/issues/8312), and the solution (for this particular resource) is to double the `$` (ex. "arn:aws:iam::1234567890:user/$${aws:username}").

This throws an error:
```
resource "aws_iam_policy" "example" {
    name        = "require_mfa"
    path        = "/"
    description = "Example"
    policy      = <<POLICY
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": [
        "iam:UploadSSHPublicKey"
      ],
      "Resource": "arn:aws:iam::1234567890:user/${aws:username}",
      "Effect": "Allow",
      "Sid": "ThisIsAnExample"
    }
  ]
}
POLICY
}
```

This is ok:
```
resource "aws_iam_policy" "example" {
    name        = "require_mfa"
    path        = "/"
    description = "Example"
    policy      = <<POLICY
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": [
        "iam:UploadSSHPublicKey"
      ],
      "Resource": "arn:aws:iam::1234567890:user/$${aws:username}",
      "Effect": "Allow",
      "Sid": "ThisIsAnExample"
    }
  ]
}
POLICY
}
```

I haven't read through the gem enough to create a PR, but at first glance this might belong in `prettify_policy`, though it sounds like there are different escaping standards for different IAM policy types, so there might need to be a more fine-tuned approach.

**Comment by gauravarora** [comment]
I am running within a docker container and I think I'm also hitting this bug. I'm on the `latest` image tag. The error I see is
```
/usr/local/bundle/gems/terraforming-0.13.2/lib/terraforming/util.rb:21:in `unescape': uninitialized class variable @@accept_charset in #<Class:CGI> (NameError)
Did you mean?  @@accept_charset
	from /usr/local/bundle/gems/terraforming-0.13.2/lib/terraforming/util.rb:21:in `prettify_policy'
	from (erb):6:in `block in apply_template'
	from (erb):1:in `each'
	from (erb):1:in `apply_template'
	from /usr/local/lib/ruby/2.4.0/erb.rb:896:in `eval'
	from /usr/local/lib/ruby/2.4.0/erb.rb:896:in `result'
	from /usr/local/bundle/gems/terraforming-0.13.2/lib/terraforming/util.rb:4:in `apply_template'
	from /usr/local/bundle/gems/terraforming-0.13.2/lib/terraforming/resource/iam_user_policy.rb:19:in `tf'
	from /usr/local/bundle/gems/terraforming-0.13.2/lib/terraforming/resource/iam_user_policy.rb:7:in `tf'
	from /usr/local/bundle/gems/terraforming-0.13.2/lib/terraforming/cli.rb:240:in `tf'
	from /usr/local/bundle/gems/terraforming-0.13.2/lib/terraforming/cli.rb:227:in `execute'
	from /usr/local/bundle/gems/terraforming-0.13.2/lib/terraforming/cli.rb:119:in `iamup'
	from /usr/local/bundle/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /usr/local/bundle/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/bundle/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /usr/local/bundle/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /usr/local/bundle/gems/terraforming-0.13.2/bin/terraforming:5:in `<top (required)>'
	from /usr/local/bundle/bin/terraforming:17:in `load'
	from /usr/local/bundle/bin/terraforming:17:in `<main>'
```

**Comment by o6uoq** [comment]
I have the same issue when declaring an AWS S3 policy under `aws_s3_bucket`, from within a module:

```
  policy = <<POLICY
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "PublicReadGetObject",
      "Effect": "Allow",
      "Principal": "*",
      "Action": "s3:GetObject",
      "Resource": "arn:aws:s3:::$${bucket}/*"
    }
  ]
}
POLICY
}
```

When running `terraform plan` it displays this:

```      policy:                      "{\n  \"Version\": \"2012-10-17\",\n  \"Statement\": [\n    {\n      \"Sid\": \"PublicReadGetObject\",\n      \"Effect\": \"Allow\",\n      \"Principal\": \"*\",\n      \"Action\": \"s3:GetObject\",\n      \"Resource\": \"arn:aws:s3:::${bucket}/*\"\n    }\n  ]\n}\n"```

^ it's not declaring the variable specified. Works when using a hardcoded name for $bucket.

**Comment by danopia** [comment]
I also ran into this original issue, when dealing with MFA policies.

#108 seems related as well.

Manually doubling the dollar signs within the policies seems to be the correct workaround for now.
