### ISSUE TITLE
`sign_request': unable to sign request without credentials set (Aws::Errors::MissingCredentialsError)

### ISSUE THREAD

**Issue by varunchandak** [dtan4/terraforming#385]
When I run this:
```$ terraforming ec2 --assume=arn:aws:iam::5XXXXXXXXXXX:role/SOME-ROLE --region=ap-south-1```

I am facing this error:
```
/usr/local/lib/ruby/gems/2.4.0/gems/aws-sdk-core-3.6.0/lib/aws-sdk-core/plugins/signature_v4.rb:70:in `sign_request': unable to sign request without credentials set (Aws::Errors::MissingCredentialsError)
	from /usr/local/lib/ruby/gems/2.4.0/gems/aws-sdk-core-3.6.0/lib/aws-sdk-core/plugins/signature_v4.rb:110:in `apply_signature'
	from /usr/local/lib/ruby/gems/2.4.0/gems/aws-sdk-core-3.6.0/lib/aws-sdk-core/plugins/signature_v4.rb:63:in `call'
	from /usr/local/lib/ruby/gems/2.4.0/gems/aws-sdk-core-3.6.0/lib/aws-sdk-core/plugins/helpful_socket_errors.rb:10:in `call'
	from /usr/local/lib/ruby/gems/2.4.0/gems/aws-sdk-core-3.6.0/lib/aws-sdk-core/plugins/retry_errors.rb:92:in `call'
	from /usr/local/lib/ruby/gems/2.4.0/gems/aws-sdk-core-3.6.0/lib/aws-sdk-core/query/handler.rb:28:in `call'
	from /usr/local/lib/ruby/gems/2.4.0/gems/aws-sdk-core-3.6.0/lib/aws-sdk-core/plugins/user_agent.rb:13:in `call'
	from /usr/local/lib/ruby/gems/2.4.0/gems/aws-sdk-core-3.6.0/lib/seahorse/client/plugins/endpoint.rb:45:in `call'
	from /usr/local/lib/ruby/gems/2.4.0/gems/aws-sdk-core-3.6.0/lib/aws-sdk-core/plugins/param_validator.rb:24:in `call'
	from /usr/local/lib/ruby/gems/2.4.0/gems/aws-sdk-core-3.6.0/lib/seahorse/client/plugins/raise_response_errors.rb:14:in `call'
	from /usr/local/lib/ruby/gems/2.4.0/gems/aws-sdk-core-3.6.0/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'
	from /usr/local/lib/ruby/gems/2.4.0/gems/aws-sdk-core-3.6.0/lib/aws-sdk-core/plugins/idempotency_token.rb:17:in `call'
	from /usr/local/lib/ruby/gems/2.4.0/gems/aws-sdk-core-3.6.0/lib/aws-sdk-core/plugins/param_converter.rb:24:in `call'
	from /usr/local/lib/ruby/gems/2.4.0/gems/aws-sdk-core-3.6.0/lib/aws-sdk-core/plugins/response_paging.rb:10:in `call'
	from /usr/local/lib/ruby/gems/2.4.0/gems/aws-sdk-core-3.6.0/lib/seahorse/client/plugins/response_target.rb:23:in `call'
	from /usr/local/lib/ruby/gems/2.4.0/gems/aws-sdk-core-3.6.0/lib/seahorse/client/request.rb:70:in `send_request'
	from /usr/local/lib/ruby/gems/2.4.0/gems/aws-sdk-core-3.6.0/lib/aws-sdk-sts/client.rb:429:in `assume_role'
	from /usr/local/lib/ruby/gems/2.4.0/gems/aws-sdk-core-3.6.0/lib/aws-sdk-core/assume_role_credentials.rb:49:in `refresh'
	from /usr/local/lib/ruby/gems/2.4.0/gems/aws-sdk-core-3.6.0/lib/aws-sdk-core/refreshing_credentials.rb:20:in `initialize'
	from /usr/local/lib/ruby/gems/2.4.0/gems/aws-sdk-core-3.6.0/lib/aws-sdk-core/assume_role_credentials.rb:40:in `initialize'
	from /usr/local/lib/ruby/gems/2.4.0/gems/terraforming-0.16.0/lib/terraforming/cli.rb:237:in `new'
	from /usr/local/lib/ruby/gems/2.4.0/gems/terraforming-0.16.0/lib/terraforming/cli.rb:237:in `configure_aws'
	from /usr/local/lib/ruby/gems/2.4.0/gems/terraforming-0.16.0/lib/terraforming/cli.rb:244:in `execute'
	from /usr/local/lib/ruby/gems/2.4.0/gems/terraforming-0.16.0/lib/terraforming/cli.rb:45:in `ec2'
	from /usr/local/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /usr/local/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /usr/local/lib/ruby/gems/2.4.0/gems/terraforming-0.16.0/bin/terraforming:5:in `<top (required)>'
	from /usr/local/bin/terraforming:23:in `load'
	from /usr/local/bin/terraforming:23:in `<main>'
```
I am using role-based aws-cli configuration, and the `assume-role` stuff is written inside `.aws/config` file as per AWS docs.

As I don't know much about ruby, any help would be appreciated.

**Comment by varunchandak** [comment]
Got this fixed as below:

```$ terraforming ec2 --assume=arn:aws:iam::5XXXXXXXXXXX:role/SOME-ROLE --region=ap-south-1 --profile=CROSS_ACCOUNT_PROFILE```
