### ISSUE TITLE
undefined method 'role_name' when running iamip

### ISSUE THREAD

**Issue by reisingerf** [dtan4/terraforming#399]
$> terraforming iamip
```
(erb):5:in `block in apply_template': undefined method `role_name' for nil:NilClass (NoMethodError)
	from (erb):1:in `each'
	from (erb):1:in `apply_template'
	from /usr/local/lib/ruby/2.4.0/erb.rb:896:in `eval'
	from /usr/local/lib/ruby/2.4.0/erb.rb:896:in `result'
	from /usr/local/bundle/gems/terraforming-0.16.0/lib/terraforming/util.rb:4:in `apply_template'
	from /usr/local/bundle/gems/terraforming-0.16.0/lib/terraforming/resource/iam_instance_profile.rb:19:in `tf'
	from /usr/local/bundle/gems/terraforming-0.16.0/lib/terraforming/resource/iam_instance_profile.rb:7:in `tf'
	from /usr/local/bundle/gems/terraforming-0.16.0/lib/terraforming/cli.rb:258:in `tf'
	from /usr/local/bundle/gems/terraforming-0.16.0/lib/terraforming/cli.rb:245:in `execute'
	from /usr/local/bundle/gems/terraforming-0.16.0/lib/terraforming/cli.rb:90:in `iamip'
	from /usr/local/bundle/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /usr/local/bundle/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/bundle/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /usr/local/bundle/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /usr/local/bundle/gems/terraforming-0.16.0/bin/terraforming:5:in `<top (required)>'
	from /usr/local/bundle/bin/terraforming:21:in `load'
	from /usr/local/bundle/bin/terraforming:21:in `<main>'
```

**Comment by codingtony** [comment]
Same error +1

**Comment by gino-u** [comment]
Same here, would love to get this working!

**Comment by rbarnette** [comment]
I am also getting this error.

**Comment by tomisaacson** [comment]
Same error.

Platform: Linux (Ubuntu 18.04)
Ruby version: ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]
Terraforming version: terraforming (0.16.0)

**Comment by Hillmonkey** [comment]
Same error. 😢 
Platform: MacOS High Sierra 10.13.6
Ruby version: ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin17]
Terraform version: Terraform v0.11.11
Terraforming version: pretty recent

**Comment by asksmruti** [comment]
Same error 😞

**Comment by Avolynsk** [comment]
Got this error yesterday. I believe I have a fix for it. Let me check it and I'll add a PR.
