### ISSUE TITLE
Topic does not exist error trying to run snss

### ISSUE THREAD

**Issue by threesquared** [dtan4/terraforming#467]
I am running version `0.18.0` on MacOS with Ruby `2.3.7p456` and am trying to run `terraforming snss` but I get the following error and stack trace:

```
/usr/local/Cellar/terraforming/0.18.0/libexec/gems/aws-sdk-core-3.51.0/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call': Topic does not exist (Aws::SNS::Errors::NotFound)
        from /usr/local/Cellar/terraforming/0.18.0/libexec/gems/aws-sdk-core-3.51.0/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'
        from /usr/local/Cellar/terraforming/0.18.0/libexec/gems/aws-sdk-core-3.51.0/lib/aws-sdk-core/plugins/idempotency_token.rb:17:in `call'
        from /usr/local/Cellar/terraforming/0.18.0/libexec/gems/aws-sdk-core-3.51.0/lib/aws-sdk-core/plugins/param_converter.rb:24:in `call'
        from /usr/local/Cellar/terraforming/0.18.0/libexec/gems/aws-sdk-core-3.51.0/lib/aws-sdk-core/plugins/response_paging.rb:10:in `call'
        from /usr/local/Cellar/terraforming/0.18.0/libexec/gems/aws-sdk-core-3.51.0/lib/seahorse/client/plugins/response_target.rb:23:in `call'
        from /usr/local/Cellar/terraforming/0.18.0/libexec/gems/aws-sdk-core-3.51.0/lib/seahorse/client/request.rb:70:in `send_request'
        from /usr/local/Cellar/terraforming/0.18.0/libexec/gems/aws-sdk-sns-1.12.0/lib/aws-sdk-sns/client.rb:759:in `get_subscription_attributes'
        from /usr/local/Cellar/terraforming/0.18.0/libexec/gems/terraforming-0.18.0/lib/terraforming/resource/sns_topic_subscription.rb:56:in `block in subscriptions'
        from /usr/local/Cellar/terraforming/0.18.0/libexec/gems/terraforming-0.18.0/lib/terraforming/resource/sns_topic_subscription.rb:52:in `map'
        from /usr/local/Cellar/terraforming/0.18.0/libexec/gems/terraforming-0.18.0/lib/terraforming/resource/sns_topic_subscription.rb:52:in `subscriptions'
        from (erb):1:in `apply_template'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/erb.rb:864:in `eval'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/erb.rb:864:in `result'
        from /usr/local/Cellar/terraforming/0.18.0/libexec/gems/terraforming-0.18.0/lib/terraforming/util.rb:4:in `apply_template'
        from /usr/local/Cellar/terraforming/0.18.0/libexec/gems/terraforming-0.18.0/lib/terraforming/resource/sns_topic_subscription.rb:19:in `tf'
        from /usr/local/Cellar/terraforming/0.18.0/libexec/gems/terraforming-0.18.0/lib/terraforming/resource/sns_topic_subscription.rb:7:in `tf'
        from /usr/local/Cellar/terraforming/0.18.0/libexec/gems/terraforming-0.18.0/lib/terraforming/cli.rb:263:in `tf'
        from /usr/local/Cellar/terraforming/0.18.0/libexec/gems/terraforming-0.18.0/lib/terraforming/cli.rb:250:in `execute'
        from /usr/local/Cellar/terraforming/0.18.0/libexec/gems/terraforming-0.18.0/lib/terraforming/cli.rb:230:in `snss'
        from /usr/local/Cellar/terraforming/0.18.0/libexec/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        from /usr/local/Cellar/terraforming/0.18.0/libexec/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        from /usr/local/Cellar/terraforming/0.18.0/libexec/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        from /usr/local/Cellar/terraforming/0.18.0/libexec/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
        from /usr/local/Cellar/terraforming/0.18.0/libexec/gems/terraforming-0.18.0/bin/terraforming:5:in `<top (required)>'
        from /usr/local/Cellar/terraforming/0.18.0/libexec/bin/terraforming:22:in `load'
        from /usr/local/Cellar/terraforming/0.18.0/libexec/bin/terraforming:22:in `<main>'
```

**Comment by harymitchell** [comment]
I experience the same issue. 

- MacOS. 
- ruby 2.3.7p456
- terraforming (0.18.0)

```
$  terraforming snss 
/Library/Ruby/Gems/2.3.0/gems/aws-sdk-core-3.94.1/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call': Topic does not exist (Aws::SNS::Errors::NotFound)
	from /Library/Ruby/Gems/2.3.0/gems/aws-sdk-core-3.94.1/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/aws-sdk-core-3.94.1/lib/aws-sdk-core/plugins/idempotency_token.rb:17:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/aws-sdk-core-3.94.1/lib/aws-sdk-core/plugins/param_converter.rb:24:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/aws-sdk-core-3.94.1/lib/aws-sdk-core/plugins/response_paging.rb:10:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/aws-sdk-core-3.94.1/lib/seahorse/client/plugins/response_target.rb:23:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/aws-sdk-core-3.94.1/lib/seahorse/client/request.rb:70:in `send_request'
	from /Library/Ruby/Gems/2.3.0/gems/aws-sdk-sns-1.22.0/lib/aws-sdk-sns/client.rb:870:in `get_subscription_attributes'
	from /Library/Ruby/Gems/2.3.0/gems/terraforming-0.18.0/lib/terraforming/resource/sns_topic_subscription.rb:56:in `block in subscriptions'
	from /Library/Ruby/Gems/2.3.0/gems/terraforming-0.18.0/lib/terraforming/resource/sns_topic_subscription.rb:52:in `map'
	from /Library/Ruby/Gems/2.3.0/gems/terraforming-0.18.0/lib/terraforming/resource/sns_topic_subscription.rb:52:in `subscriptions'
	from (erb):1:in `apply_template'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/erb.rb:864:in `eval'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/erb.rb:864:in `result'
	from /Library/Ruby/Gems/2.3.0/gems/terraforming-0.18.0/lib/terraforming/util.rb:4:in `apply_template'
	from /Library/Ruby/Gems/2.3.0/gems/terraforming-0.18.0/lib/terraforming/resource/sns_topic_subscription.rb:19:in `tf'
	from /Library/Ruby/Gems/2.3.0/gems/terraforming-0.18.0/lib/terraforming/resource/sns_topic_subscription.rb:7:in `tf'
	from /Library/Ruby/Gems/2.3.0/gems/terraforming-0.18.0/lib/terraforming/cli.rb:263:in `tf'
	from /Library/Ruby/Gems/2.3.0/gems/terraforming-0.18.0/lib/terraforming/cli.rb:250:in `execute'
	from /Library/Ruby/Gems/2.3.0/gems/terraforming-0.18.0/lib/terraforming/cli.rb:230:in `snss'
	from /Library/Ruby/Gems/2.3.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /Library/Ruby/Gems/2.3.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	from /Library/Ruby/Gems/2.3.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
	from /Library/Ruby/Gems/2.3.0/gems/terraforming-0.18.0/bin/terraforming:5:in `<top (required)>'
	from /usr/local/bin/terraforming:22:in `load'
	from /usr/local/bin/terraforming:22:in `<main>'
```
